# Generated by Django 3.2.9 on 2022-10-15 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
