# Generated by Django 3.2.9 on 2022-10-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
