# Generated by Django 4.1.2 on 2022-10-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_profile_thumbnail_profile_thumbnail_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='thumbnail_url',
            new_name='thumbnail',
        ),
    ]
