# Generated by Django 4.1.2 on 2022-10-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_imagemodel_created_by_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='filename',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
