# Generated by Django 4.1.2 on 2022-10-16 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_imagemodel_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='filename',
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
