# Generated by Django 4.1.2 on 2022-10-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_imagemodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='profile',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
