# Generated by Django 4.1.2 on 2022-10-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_rename_thumbnail_url_profile_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
